[[p]]{source}
  [[div class="row-fluid"]]
    [[div class="span12"]] [[img class="pull-right img-ofba" src="images/ofba/events/thumbs/20140518_Ballet_El_corsario.jpg" alt="" /]]
      [[h4]]Temporada 2014[[/h4]]
      [[h5]]Ciclo de Ballet[[/h5]]
      [[h5]]Teatro Colón[[/h5]]
      [[br /]]
      [[p]][[strong]]Funciones: Domingo 18, 17:00; Martes 20, Miércoles 21, Jueves 22, Viernes 23 y Sábado 24 de mayo de 2014, 20:30[[/strong]][[/p]]
      [[p]][[strong]]Director: José Luis Domínguez[[/strong]][[/p]]
      [[p]] [[strong]]Ballet Estable del Teatro Colón, Director: Lidia Segni[[/strong]]
        [[br /]]
        [[br /]] Música: Riccardo Drigo, Adolphe Adam, Léo Delibes
        [[br /]] Coreografía: Anna-Marie Holmes. Reposición coreográfica: Lidia Segni
        [[br /]] Bailarines solistas: Karina Olmedo y Nadia Muzyca (Medora); Federico Fernández (Conrad); Edgardo Trabalón y Alejandro Parente (Alí) [[/p]]
    [[/div]]
  [[/div]]
  [[div class="row-fluid"]]
    [[div class="span12"]]
      [[br /]]
      [[br /]] [[/div]]
  [[/div]]
  [[div class="row-fluid"]]
    [[div class="span4"]]
      [[div id="mnuProgramaMano"  class="accordion"]]
        [[div class="accordion-inner"]] [[span style="color: #FCEAC3;"]]Programa de mano[[/span]] [[/div]]
      [[/div]]
    [[/div]]
    [[div class="span4"]]
      [[div id="mnuGaleriaImagenes" class="accordion"]]
        [[div class="accordion-inner"]] [[span style="color: #FCEAC3;"]]Galería de imágenes[[/span]] [[/div]]
      [[/div]]
    [[/div]]
    [[div class="span4"]]
      [[div id="mnuRegistroFonografico" class="accordion"]]
        [[div class="accordion-inner"]] [[span style="color: #FCEAC3;"]]Registro fonográfico[[/span]] [[/div]]
      [[/div]]
    [[/div]]
  [[/div]]
  [[div class="row-fluid"]]
    [[div class="span4"]]
      [[div id="mnuAnuncios" class="accordion"]]
        [[div class="accordion-inner"]] [[span style="color: #FCEAC3;"]]Anuncios[[/span]] [[/div]]
      [[/div]]
    [[/div]]
    [[div class="span4"]]
      [[div id="mnuGacetillaPrensa" class="accordion"]]
        [[div class="accordion-inner"]] [[span style="color: #FCEAC3;"]]Gacetilla de prensa[[/span]] [[/div]]
      [[/div]]
    [[/div]]
    [[div class="span4"]]
      [[div id="mnuRegistroFilmografico" class="accordion"]]
        [[div class="accordion-inner"]] [[span style="color: #FCEAC3;"]]Registro filmográfico[[/span]] [[/div]]
      [[/div]]
    [[/div]]
  [[/div]]
  [[div class="row-fluid"]]
    [[div class="span4"]]
      [[div id="mnuCriticas" class="accordion"]]
        [[div class="accordion-inner"]] [[span style="color: #FCEAC3;"]]Críticas[[/span]] [[/div]]
      [[/div]]
    [[/div]]
  [[/div]] {/source}[[/p]]
