[[p]]
  {source}
  [[div class="row-fluid"]]
    [[div class="span12"]]
      [[img class="pull-right img-ofba" src="images/ofba/events/thumbs/20140710_A10_Peter_Donohoe_piano.jpg" alt="" /]]
      [[h4]]Temporada 2014[[/h4]]
      [[h5]]Ciclo de Abono[[/h5]]
      [[h5]]Teatro Colón[[/h5]]
      [[br /]]
      [[p]][[strong]]Jueves 10 de julio de 2014, 20:30[[/strong]][[/p]]
      [[p]][[strong]]Director: Ira Levin[[/strong]][[/p]]
      [[p]][[strong]]Solista: Peter Donohoe, piano[[/strong]]
        [[br /]]
        [[br /]]
      [[/p]]
      [[p]] Richard Strauss: Burleske, para piano y orquesta en Re menor, Op. 85
        [[br /]] Franz Liszt: Fantasía húngara para piano y orquesta
        [[br /]] Robert Schumann: Sinfonía Nº 2 en Do Mayor, Op. 61
      [[/p]]
    [[/div]]
  [[/div]]
  [[div class="row-fluid"]]
    [[div class="span12"]]
      [[br /]]
      [[br /]]
    [[/div]]
  [[/div]]
  [[div class="row-fluid"]]
    [[div class="span4"]]
      [[div id="mnuProgramaMano" class="accordion"]]
        [[div class="accordion-inner"]]
          [[span style="color: #FCEAC3;"]]Programa de mano[[/span]]
        [[/div]]
      [[/div]]
    [[/div]]
    [[div class="span4"]]
      [[div id="mnuGaleriaImagenes" class="accordion"]]
        [[div class="accordion-inner"]]
          [[span style="color: #FCEAC3;"]]Galería de imágenes[[/span]]
        [[/div]]
      [[/div]]
    [[/div]]
    [[div class="span4"]]
      [[div id="mnuRegistroFonografico" class="accordion"]]
        [[div class="accordion-inner"]]
          [[span style="color: #FCEAC3;"]]Registro fonográfico[[/span]]
        [[/div]]
      [[/div]]
    [[/div]]
  [[/div]]
  [[div class="row-fluid"]]
    [[div class="span4"]]
      [[div id="mnuAnuncios" class="accordion"]]
        [[div class="accordion-inner"]]
          [[span style="color: #FCEAC3;"]]Anuncios[[/span]]
        [[/div]]
      [[/div]]
    [[/div]]
    [[div class="span4"]]
      [[div id="mnuGacetillaPrensa" class="accordion"]]
        [[div class="accordion-inner"]]
          [[span style="color: #FCEAC3;"]]Gacetilla de prensa[[/span]]
        [[/div]]
      [[/div]]
    [[/div]]
    [[div class="span4"]]
      [[div id="mnuRegistroFilmografico" class="accordion"]]
        [[div class="accordion-inner"]] [[span style="color: #FCEAC3;"]]Registro filmográfico[[/span]] [[/div]]
      [[/div]]
    [[/div]]
  [[/div]]
  [[div class="row-fluid"]]
    [[div class="span4"]]
      [[div id="mnuCriticas" class="accordion"]]
        [[div class="accordion-inner"]] [[span style="color: #FCEAC3;"]]Críticas[[/span]] [[/div]]
      [[/div]]
    [[/div]]
  [[/div]] {/source}[[/p]]
